// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

package com.company.restclient;

public final class HandshakeRecord {


    /*package*/ final String mResponseStatus;

    public HandshakeRecord(
            String responseStatus) {
        this.mResponseStatus = responseStatus;
    }

    public String getResponseStatus() {
        return mResponseStatus;
    }

    @Override
    public String toString() {
        return "HandshakeRecord{" +
                "mResponseStatus=" + mResponseStatus +
        "}";
    }

}
