// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#pragma once

#include "djinni_support.hpp"
#include "instance.hpp"

namespace djinni_generated {

class NativeInstance final : ::djinni::JniInterface<::restclient::Instance, NativeInstance> {
public:
    using CppType = std::shared_ptr<::restclient::Instance>;
    using CppOptType = std::shared_ptr<::restclient::Instance>;
    using JniType = jobject;

    using Boxed = NativeInstance;

    ~NativeInstance();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeInstance>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeInstance>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeInstance();
    friend ::djinni::JniClass<NativeInstance>;
    friend ::djinni::JniInterface<::restclient::Instance, NativeInstance>;

};

}  // namespace djinni_generated
