// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#pragma once

#include "api_handshake.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeApiHandshake final : ::djinni::JniInterface<::restclient::ApiHandshake, NativeApiHandshake> {
public:
    using CppType = std::shared_ptr<::restclient::ApiHandshake>;
    using CppOptType = std::shared_ptr<::restclient::ApiHandshake>;
    using JniType = jobject;

    using Boxed = NativeApiHandshake;

    ~NativeApiHandshake();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeApiHandshake>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeApiHandshake>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeApiHandshake();
    friend ::djinni::JniClass<NativeApiHandshake>;
    friend ::djinni::JniInterface<::restclient::ApiHandshake, NativeApiHandshake>;

};

}  // namespace djinni_generated
