// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#pragma once

#include "djinni_support.hpp"
#include "handshake_result_record.hpp"

namespace djinni_generated {

class NativeHandshakeResultRecord final {
public:
    using CppType = ::helloworld::HandshakeResultRecord;
    using JniType = jobject;

    using Boxed = NativeHandshakeResultRecord;

    ~NativeHandshakeResultRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeHandshakeResultRecord();
    friend ::djinni::JniClass<NativeHandshakeResultRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/mycompany/helloworld/HandshakeResultRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mResponseStatus { ::djinni::jniGetFieldID(clazz.get(), "mResponseStatus", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
