// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#pragma once

#include "djinni_support.hpp"
#include "handshake_record.hpp"

namespace djinni_generated {

class NativeHandshakeRecord final {
public:
    using CppType = ::restclient::HandshakeRecord;
    using JniType = jobject;

    using Boxed = NativeHandshakeRecord;

    ~NativeHandshakeRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeHandshakeRecord();
    friend ::djinni::JniClass<NativeHandshakeRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/cortex/restclient/HandshakeRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mResponseStatus { ::djinni::jniGetFieldID(clazz.get(), "mResponseStatus", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
