// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#include "NativeHandshakeRecord.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeHandshakeRecord::NativeHandshakeRecord() = default;

NativeHandshakeRecord::~NativeHandshakeRecord() = default;

auto NativeHandshakeRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeHandshakeRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.responseStatus)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeHandshakeRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeHandshakeRecord>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mResponseStatus))};
}

}  // namespace djinni_generated
