// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

package com.cortex.restclient;

public final class HandshakeResultRecord {


    /*package*/ final String mResponseStatus;

    public HandshakeResultRecord(
            String responseStatus) {
        this.mResponseStatus = responseStatus;
    }

    public String getResponseStatus() {
        return mResponseStatus;
    }

    @Override
    public String toString() {
        return "HandshakeResultRecord{" +
                "mResponseStatus=" + mResponseStatus +
        "}";
    }

}
