// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import "HWHandshakeResultRecord.h"
#import <Foundation/Foundation.h>
@class HWApiHandshake;


@interface HWApiHandshake : NSObject

+ (nullable HWApiHandshake *)create;

- (nonnull HWHandshakeResultRecord *)handshake:(nonnull NSString *)udId
                                    appVersion:(nonnull NSString *)appVersion
                                     osVersion:(nonnull NSString *)osVersion
                                        osType:(nonnull NSString *)osType;

@end
