// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#include "api_handshake.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWApiHandshake;

namespace djinni_generated {

class ApiHandshake
{
public:
    using CppType = std::shared_ptr<::helloworld::ApiHandshake>;
    using CppOptType = std::shared_ptr<::helloworld::ApiHandshake>;
    using ObjcType = HWApiHandshake*;

    using Boxed = ApiHandshake;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

