// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import "HWHandshakeResultRecord.h"
#include "handshake_result_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWHandshakeResultRecord;

namespace djinni_generated {

struct HandshakeResultRecord
{
    using CppType = ::helloworld::HandshakeResultRecord;
    using ObjcType = HWHandshakeResultRecord*;

    using Boxed = HandshakeResultRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
