// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import <Foundation/Foundation.h>

@interface HWHandshakeResultRecord : NSObject
- (nonnull instancetype)initWithResponseStatus:(nonnull NSString *)responseStatus;
+ (nonnull instancetype)handshakeResultRecordWithResponseStatus:(nonnull NSString *)responseStatus;

@property (nonatomic, readonly, nonnull) NSString * responseStatus;

@end
