// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import "HWHandshakeResultRecord.h"


@implementation HWHandshakeResultRecord

- (nonnull instancetype)initWithResponseStatus:(nonnull NSString *)responseStatus
{
    if (self = [super init]) {
        _responseStatus = [responseStatus copy];
    }
    return self;
}

+ (nonnull instancetype)handshakeResultRecordWithResponseStatus:(nonnull NSString *)responseStatus
{
    return [[self alloc] initWithResponseStatus:responseStatus];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p responseStatus:%@>", self.class, (void *)self, self.responseStatus];
}

@end
