// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#import "RCHandshakeResultRecord.h"
#import <Foundation/Foundation.h>
@class RCApiHandshake;


@interface RCApiHandshake : NSObject

+ (nullable RCApiHandshake *)create;

- (nonnull RCHandshakeResultRecord *)handshake:(nonnull NSString *)udId
                                    appVersion:(nonnull NSString *)appVersion
                                     osVersion:(nonnull NSString *)osVersion
                                        osType:(nonnull NSString *)osType;

@end
