// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#import "RCHandshakeResultRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto HandshakeResultRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.responseStatus)};
}

auto HandshakeResultRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[RCHandshakeResultRecord alloc] initWithResponseStatus:(::djinni::String::fromCpp(cpp.responseStatus))];
}

}  // namespace djinni_generated
