// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#import "RCHandshakeRecord.h"
#include "handshake_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class RCHandshakeRecord;

namespace djinni_generated {

struct HandshakeRecord
{
    using CppType = ::restclient::HandshakeRecord;
    using ObjcType = RCHandshakeRecord*;

    using Boxed = HandshakeRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
