// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#import "RCHandshakeResultRecord.h"
#include "handshake_result_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class RCHandshakeResultRecord;

namespace djinni_generated {

struct HandshakeResultRecord
{
    using CppType = ::restclient::HandshakeResultRecord;
    using ObjcType = RCHandshakeResultRecord*;

    using Boxed = HandshakeResultRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
