// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#import <Foundation/Foundation.h>

@interface RCHandshakeRecord : NSObject
- (nonnull instancetype)initWithResponseStatus:(nonnull NSString *)responseStatus;
+ (nonnull instancetype)handshakeRecordWithResponseStatus:(nonnull NSString *)responseStatus;

@property (nonatomic, readonly, nonnull) NSString * responseStatus;

@end
