// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#import "RCInstance+Private.h"
#import "RCInstance.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "RCHandshakeRecord+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface RCInstance ()

- (id)initWithCpp:(const std::shared_ptr<::restclient::Instance>&)cppRef;

@end

@implementation RCInstance {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::restclient::Instance>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::restclient::Instance>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable RCInstance *)create {
    try {
        auto objcpp_result_ = ::restclient::Instance::create();
        return ::djinni_generated::Instance::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull RCHandshakeRecord *)handshake:(nonnull NSString *)udId
                              appVersion:(nonnull NSString *)appVersion
                               osVersion:(nonnull NSString *)osVersion
                                  osType:(nonnull NSString *)osType {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->handshake(::djinni::String::toCpp(udId),
                                                             ::djinni::String::toCpp(appVersion),
                                                             ::djinni::String::toCpp(osVersion),
                                                             ::djinni::String::toCpp(osType));
        return ::djinni_generated::HandshakeRecord::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Instance::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Instance::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<RCInstance>(cpp);
}

}  // namespace djinni_generated

@end
