// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#import "RCHandshakeRecord.h"
#import <Foundation/Foundation.h>
@class RCInstance;


@interface RCInstance : NSObject

+ (nullable RCInstance *)create;

- (nonnull RCHandshakeRecord *)handshake:(nonnull NSString *)udId
                              appVersion:(nonnull NSString *)appVersion
                               osVersion:(nonnull NSString *)osVersion
                                  osType:(nonnull NSString *)osType;

@end
