// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#pragma once

#include <memory>
#include <string>

namespace helloworld {

struct HandshakeResultRecord;

class ApiHandshake {
public:
    virtual ~ApiHandshake() {}

    static std::shared_ptr<ApiHandshake> create();

    virtual HandshakeResultRecord handshake(const std::string & udId, const std::string & appVersion, const std::string & osVersion, const std::string & osType) = 0;
};

}  // namespace helloworld
