// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#pragma once

#include <string>
#include <utility>

namespace restclient {

struct HandshakeRecord final {
    std::string responseStatus;

    HandshakeRecord(std::string responseStatus_)
    : responseStatus(std::move(responseStatus_))
    {}
};

}  // namespace restclient
