// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from restclient.djinni

#pragma once

#include <memory>
#include <string>

namespace restclient {

struct HandshakeRecord;

class Instance {
public:
    virtual ~Instance() {}

    static std::shared_ptr<Instance> create();

    virtual HandshakeRecord handshake(const std::string & udId, const std::string & appVersion, const std::string & osVersion, const std::string & osType) = 0;
};

}  // namespace restclient
